///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TwoSimpleThings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TwoSimpleThingsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("9ef8969e-dc14-4d17-8dba-357326284176")]
    public partial class TwoSimpleThingsRepository : RepoGenBaseFolder
    {
        static TwoSimpleThingsRepository instance = new TwoSimpleThingsRepository();
        TwoSimpleThingsRepositoryFolders.KULeuvenAppFolder _kuleuven;

        /// <summary>
        /// Gets the singleton class instance representing the TwoSimpleThingsRepository element repository.
        /// </summary>
        [RepositoryFolder("9ef8969e-dc14-4d17-8dba-357326284176")]
        public static TwoSimpleThingsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TwoSimpleThingsRepository() 
            : base("TwoSimpleThingsRepository", "/", null, 0, false, "9ef8969e-dc14-4d17-8dba-357326284176", ".\\RepositoryImages\\TwoSimpleThingsRepository9ef8969e.rximgres")
        {
            _kuleuven = new TwoSimpleThingsRepositoryFolders.KULeuvenAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("9ef8969e-dc14-4d17-8dba-357326284176")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The KULeuven folder.
        /// </summary>
        [RepositoryFolder("8d48fe90-e61e-4563-b188-d892caf3b7b1")]
        public virtual TwoSimpleThingsRepositoryFolders.KULeuvenAppFolder KULeuven
        {
            get { return _kuleuven; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TwoSimpleThingsRepositoryFolders
    {
        /// <summary>
        /// The KULeuvenAppFolder folder.
        /// </summary>
        [RepositoryFolder("8d48fe90-e61e-4563-b188-d892caf3b7b1")]
        public partial class KULeuvenAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _logoInfo;

            /// <summary>
            /// Creates a new KULeuven  folder.
            /// </summary>
            public KULeuvenAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KULeuven", "/dom[@domain='www.kuleuven.be']", parentFolder, 5000, null, false, "8d48fe90-e61e-4563-b188-d892caf3b7b1", "")
            {
                _logoInfo = new RepoItemInfo(this, "Logo", ".//a[@class='navbar-brand']/img[@class='logo']", "", 1000, null, "ab135c9e-8d24-47ce-981c-16ddedb7f2fb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8d48fe90-e61e-4563-b188-d892caf3b7b1")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8d48fe90-e61e-4563-b188-d892caf3b7b1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Logo item.
            /// </summary>
            [RepositoryItem("ab135c9e-8d24-47ce-981c-16ddedb7f2fb")]
            public virtual Ranorex.ImgTag Logo
            {
                get
                {
                    return _logoInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Logo item info.
            /// </summary>
            [RepositoryItemInfo("ab135c9e-8d24-47ce-981c-16ddedb7f2fb")]
            public virtual RepoItemInfo LogoInfo
            {
                get
                {
                    return _logoInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
