///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TwoSimpleThings.RecordingsOpleidingsAanbod
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The controleerKuLeuvenWebsite recording.
    /// </summary>
    [TestModule("7e693ae9-2099-4cab-a825-dc4ee4894701", ModuleType.Recording, 1)]
    public partial class controleerKuLeuvenWebsite : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::TwoSimpleThings.TwoSimpleThingsRepository repository.
        /// </summary>
        public static global::TwoSimpleThings.TwoSimpleThingsRepository repo = global::TwoSimpleThings.TwoSimpleThingsRepository.Instance;

        static controleerKuLeuvenWebsite instance = new controleerKuLeuvenWebsite();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public controleerKuLeuvenWebsite()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static controleerKuLeuvenWebsite Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            codeCollectionKuLeuvenOpleidingen.controleerWebsiteGeopend();
            Delay.Milliseconds(0);
            
            codeCollectionKuLeuvenOpleidingen.controleerWebsiteLogo();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
